# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Friday',
            new_name='Day',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Monday',
            new_name='Daynumber',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Saturday',
            new_name='_10AM',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Sunday',
            new_name='_11AM',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Thursday',
            new_name='_9AM',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Wednesday',
        ),
    ]
