# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregis',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 9, 25, 11, 18, 45, 785751, tzinfo=utc), upload_to='pictures'),
            preserve_default=False,
        ),
    ]
